version: 2

sphinx:
  configuration: docs/conf.py
formats: all
python:
  version: "3.8"
  install:
    - requirements: requirements_dev.txt
    - requirements: requirements.txt
    - method: pip
      path: .