language: python
python:
  - 3.8
  - 3.7
  # - 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: maurol2999
  password:
    secure: hP6Z5cyCNG/MM5HJ26mMCJQygKXKe1zAiq2f3puvZtB0HmnXZEvRar1nmenKSXlBzxG40npMHYfdCrpsAJ9HJUNX6g5sr+htn+Firs2/w4onLZt9qCwMK0HpFo2K4Nmq0ibNra77Dh1HwdohWunappNBBgzT0JdaC3WkAtQTADB8+fLSWzkgKij+tPY4aN7sA/5PO44Li4EclY04aIl9zCBwIDLvaqthzd5i29lkvWuhuZLrJLfWY6/QxFzSm0S7T6h1EksOS5nDGnpPBqlGPsD5Aa44T3yzUmVLhz60IaoIg3Ym1Fdv0ythR/BaHhAvyMpRGa3KrSGiqsiHeBLyH8vkYQIWKFtXcFHIKZymoW8MCRYdRpDGQAO6SeCXasA4iV3p8ARh+vWvtcLFwsKggSNdH8UE1EpVLBrriHF4+bxMxzE72vfr/c7fLYX2f6kIwyB/IIHAbXVVeSav44PZSIqyore2B17kjytdvsFcGpoaUz9KISjFrM1M/AIbWXTNViVWoaaX927KLJKcjRGbyJBndvPL4pLK/A0C/VhxHERM2iM3UEeFxRSdcyiNWaroTG+82Mc8daZZkn+o9CoXYnqdMcZffGQxIRmIYhHNY+pRW9MhL2Ykxylhyef1ZnVONnZ47vAFJtMUn/Jh83VyAQlyKvHZfvm0/S90rbae1bU=
  on:
    tags: true
    repo: MauroLuzzatto/explainy
    python: 3.8
