language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: maurol2999
  password:
    secure: VtEgdKIdqzMXwXW6L0ED+U9fDwcVhtwO2/wDyEwOSYHPdTywMmrld0aqN5gP5Ul3YyPkL4bxxRzrhF6RUmQnYOR9ij4tmefkRJEocSxbm5wPlaKBXW/11zEn7YT1Y1Y8zbTJbA0QBndiEqfav+IeobulwB4+xrRKiWT2u6oQZg2Ni265PDIGzi/ucMoBWmq/13QTseJ3sYu0cV6WNidF5qpY6kpdklyLsdgjAKQVvFeDLKYmgRt2PkIIU33g27JrsOVCT9fdbNxW8nf6jmfvcBJ7GTRGKmA/v0cHlVjva2/9micEZTVKaRCe6neQ9VTVFmKKTKC92a3FgOmCjFXDo+F6gOW99YE9i0yn8SWY1zANQmu0yK3cYgOg2U+rToTPdWYDNqfP07Ne1wHmEEH0dl12aaVEiuKiaZ8oo8z4ZAflt5O0NWMalu368idhNJ5Vi4H9atKMFtdKwr+BHd8RIiT4HgQCaGNXzaHdZzuPAzW2QpuRtnbF1q1mzQN/fG/u6iEi1oM5FZRs08X+xGSXHR6U0RoPoqkWF9/+qDtzVEpqRNhvnLbhlbw/j37A3V4sAYo77cky77Y1o/re3lsfEd/T+JCSPr9rQ3andj/H80unPnSaZVcAaqdIEO1WbK1wusqOeFSD/lcBYBxtIY0hH6U+/CxOpfz4uG8wYGpqzac=
  on:
    tags: true
    repo: MauroLuzzatto/explainy
    python: 3.8
