# .github/workflows/tests.yml
name: Run tests for multiple python versions
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

        # caching pip dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
            path: ~/.cache/pip
            key: pip-requirements-${{ hashFiles('**/requirements.txt') }}
    
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Install testing dependencies
        run: |
            pip install ./
            pip install pytest

      - name: Test with pytest
        run: |
            pytest 
